https-portal:
services:
  image: steveltn/https-portal
  ports:
    - 80:80
    - 443:443
  links:
    - webserver
  environment:
    - "DOMAINS=fuzzylogic.me -> http://webserver"

webserver:
  build: ./docker/webserver
  image: fuzzylogic_web
  volumes:
      - /home/fuzzylogic/code/dist:/var/www/html
  links:
    - db

db: 
  image: mysql:5.7
  ports: 
    - "4407:3306"
  volumes:
    - ./db:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=docker
    - MYSQL_DATABASE=db_fuzzylogic



