version: '2'

services:
  webserver:
    build: ./docker/webserver
    image: fuzzylogic_web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/fuzzylogic/code/dist:/var/www/html
    links:
      - db

  db:
    image: mysql:5.7
    ports: 
      - "4407:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=db_fuzzylogic

