[build]
	command = "gulp && eleventy"
	publish = "dist"

[[redirects]]
  from = "/bytes/mac-talla-nan-creag-the-sorrow-of-derdiu"
  to = "/bytes/mac-talla-nan-creag-the-sorrow-of-derdriu"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=18144000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=18144000"
