[build]
	command = "gulp && eleventy"
	publish = "dist"

[[headers]]
  for = "*.otf"
  [headers.values]
    Cache-Control = "public, max-age=3600"
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=3600"
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=3600"
