[build]
  command = "npm run build"
  publish = "_site"
  functions = "functions"

# Opt out of Google’s FLoC origin trial (https://adactio.com/journal/18046)
[[headers]]
    for = "/*"
    [headers.values]
        Permissions-Policy = "interest-cohort=()"

# Set far-future expires on .woff2 and .woff files.
# Was needed for Netlify in the past, but could try removing.
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=18144000"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=18144000"

# Redirect old blog URLs to new Journal URLs
[[redirects]]
  from = "/thoughts/current-reading-1984-by-george-orwell"
  to = "/posts/1984-by-george-orwell/"
  status = 301

[[redirects]]
  from = "/thoughts/flexible-tag-style-collections-and-pages-for-non-tag-key-in-eleventy/"
  to = "/posts/flexible-tag-like-functionality-for-custom-keys-in-eleventy/"
  status = 301

[[redirects]]
  from = "/posts/progressive-enhancement-heuristics/"
  to = "/posts/browser-support-heuristics/"
  status = 301

[[redirects]]
  from = "/.well-known/avatar"
  to = "/.well-known/avatar.jpg"
  status = 200

[[redirects]]
  from = "/blog/"
  to = "/posts/"
  status = 301

[[redirects]]
  from = "/thoughts/*"
  to = "/posts/:splat/"
  status = 301

[[redirects]]
  from = "/bytes/*"
  to = "/posts/:splat/"
  status = 301

[[redirects]]
  from = "/links/*"
  to = "/posts/:splat/"
  status = 301

[[redirects]]
  from = "/sounds/*"
  to = "/posts/:splat/"
  status = 301
