backend:
  name: git-gateway
  branch: v3
publish_mode: editorial_workflow
media_folder: "img/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Meta description", name: "description", widget: "string"}
      - {label: "Note with title", name: "noteWithTitle", widget: "boolean", default: false, required: false}
      - {label: "Link Target", name: "noteWithTitle", widget: "string", required: false}
      - {label: "Page-specific robots directive", name: "pageSpecificRobotsDirective", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime", default: {{now}}, date_format: "YYYY-MM-DD", time_format: "HH:mm"}
      - {label: "tags", name: "tags", widget: "list", ["link"]}
      - {label: "Location", name: "location", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
