backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: v3
site_url: https://v4.fuzzylogic.me
media_folder: "_site/img/uploads"
media_library:
  name: cloudinary
  config:
    cloud_name: fuzzylogic
    api_key: 389853243577723

# publish_mode: editorial_workflow
collections:
  - label: "Post"
    name: "post"
    folder: "posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", default: "Note 2020-10-25T16:00:58: Blah" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string", required: false }
      - { label: "Link Target", name: "linkTarget", widget: "string", required: false, comment: "For bookmarks only" }
      - { label: "Body", name: "body", widget: "markdown", default: "Intro text for image note with no excerpt divider {% if app.environment == \"prod\" %}<figure>{% respimg \"https://res.cloudinary.com/fuzzylogic/image/upload/v1604167985/Larry_sRun_oil4hj.jpg\", \"Charity run for FreeAgent\", \"(min-width: 1600px) 646px, (min-width: 700px) 612px, 91.58vw\" %}<figcaption>Photo by Bob</figcaption></figure>{% endif %} *delete me here’s how to do a Mixcloud embed delete me* <iframe title=\"Title\" width=\"100%\" height=\"120\" src=\"https://www.mixcloud.com/widget/iframe/?hide_cover=1&feed=%2FRadioMagnetic%2Flothian-no-borders-ep-2%2F\" frameborder=\"0\" ></iframe> *delete me When adding an excerpt don’t add an empty line before the three dashes delete me*  --- body text, add an empty line after the three dashes before this. | For an entry (rather than note) with an image, add it as the mainImage so it shows in lists, then add an empty excerpt (is this necessary?), then start the body content with the main image for the post page <figure>{% respimg \"\" + mainImage.url + \"\", \"\" + mainImage.alt + \"\", \"(min-width: 1600px) 646px, (min-width: 700px) 612px, 91.58vw\", 320, mainImage.aspectRatioHeight %}<figcaption>{{ mainImage.figcaption }}</figcaption></figure> | code example <figure>``` css *add line break here* .post {display: grid;} *add line break here*``` *add line break here* </figure> | * deleteme new music note example * Just got this: Nat Birchall meets Al Breadwinner – Upright Living LP. Roots reggae and dub instrumentals from sunny Manchester. Current jam: Wise man style / Dub of the Prophet. <https://bit.ly/3feSzRP> <div class=\"aspect-ratio-wide\"><iframe title=\"Nat Birchall meets Al Breadwinner – Wise Man Style / Dub of the Prophet\" width=\"560\" height=\"315\" src=\"https://www.youtube-nocookie.com/embed/101Ygbe8U50\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></div>" }
      - { label: "Featured Image", name: "featuredImage", widget: "image", required: false }
      - { label: "Main Image", name: "mainImage.url", widget: "image", required: false }
      - { label: "Main Image Alt", name: "mainImage.alt", widget: "string", required: false }
      - { label: "Main Image Is Anchor", name: "mainImage.isAnchor", widget: "boolean", default: false, required: false }
      - { label: "Main Image Aspect Ratio Width", name: "mainImage.aspectRatioWidth", widget: "number", required: false }
      - { label: "Main Image Aspect Ratio Height", name: "mainImage.aspectRatioHeight", widget: "number", required: false }
      - { label: "Main Image Caption", name: "mainImage.caption", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }

  - label: "Record"
    name: "record"
    folder: "posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", default: "Artist – Title" }
      - { label: "Note with Title?", name: "noteWithTitle", widget: "boolean", default: true, required: false }
      - { label: "Description", name: "description", widget: "string", default: "Record Shopping: Artist – Title" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Location", name: "location", widget: "string", required: false, default: "Glasgow" }
      - { label: "Body", name: "body", widget: "markdown", default: "Roots reggae and dub instrumentals from sunny Manchester. Favourite track: Wise man style / Dub of the Prophet. <https://bit.ly/3feSzRP> <div class=\"aspect-ratio-wide\"><iframe title=\"Artist – Title\" width=\"560\" height=\"315\" src=\"https://www.youtube-nocookie.com/embed/101Ygbe8U50\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe></div>" }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, default: [ "note", "music", "record", "vinyl", "shopping", "recordshopping" ] }
